### ISSUE TITLE
Failed to execute script 'classpath*:alfresco/site-webscripts/org/alfresco/components/dashlets/my-sites.get.js'

### ISSUE THREAD

**Issue by outsider01** [loftuxab/alfresco-ubuntu-install#108]
After installing Alfresco with this great script i created a new user but that failed. 
I restarted the server and now i get a 500 errorpage and the share.log states:
Failed to execute script 'classpath*:alfresco/site-webscripts/org/alfresco/components/dashlets/my-sites.get.js'
  during processing of IMAP server status configuration from Alfresco: 10120000 Unable to retrieve IMAP server status from Alfresco: 401
        at org.springframework.extensions.webscripts.processor.JSScriptProcessor.executeScript(JSScriptProcessor.java:217)
        at org.springframework.extensions.webscripts.AbstractWebScript.executeScript(AbstractWebScript.java:1376)
        at org.springframework.extensions.webscripts.DeclarativeWebScript.execute(DeclarativeWebScript.java:86)
        at org.springframework.extensions.webscripts.PresentationContainer.executeScript(PresentationContainer.java:70)
        at org.springframework.extensions.webscripts.LocalWebScriptRuntimeContainer.executeScript(LocalWebScriptRuntimeContainer.java:240)
        at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:399)
        at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:210)
        at org.springframework.extensions.webscripts.WebScriptProcessor.executeBody(WebScriptProcessor.java:311)
        at org.springframework.extensions.surf.render.AbstractProcessor.execute(AbstractProcessor.java:58)
        at org.springframework.extensions.surf.render.RenderService.process(RenderService.java:602)
        at org.springframework.extensions.surf.render.RenderService.renderSubComponent(RenderService.java:508)
        at org.springframework.extensions.surf.render.RenderService.renderChromeInclude(RenderService.java:1294)
        at org.springframework.extensions.directives.ChromeIncludeFreeMarkerDirective.execute(ChromeIncludeFreeMarkerDirective.java:82)
        at freemarker.core.Environment.visit(Environment.java:341)
        at freemarker.core.UnifiedCall.accept(UnifiedCall.java:136)
        at freemarker.core.Environment.visit(Environment.java:265)
        at freemarker.core.MixedContent.accept(MixedContent.java:93)
        at freemarker.core.Environment.visit(Environment.java:265)
        at freemarker.core.IfBlock.accept(IfBlock.java:84)
        at freemarker.core.Environment.visit(Environment.java:265)
        at freemarker.core.MixedContent.accept(MixedContent.java:93)
        at freemarker.core.Environment.visit(Environment.java:265)
        at freemarker.core.Environment.process(Environment.java:243)
        at org.springframework.extensions.webscripts.processor.FTLTemplateProcessor.process(FTLTemplateProcessor.java:192)
        at org.springframework.extensions.webscripts.WebTemplateProcessor.executeBody(WebTemplateProcessor.java:439)
        at org.springframework.extensions.surf.render.AbstractProcessor.execute(AbstractProcessor.java:58)
        at org.springframework.extensions.surf.render.RenderService.processRenderable(RenderService.java:206)
        at org.springframework.extensions.surf.render.bean.ChromeRenderer.body(ChromeRenderer.java:96)
        at org.springframework.extensions.surf.render.AbstractRenderer.render(AbstractRenderer.java:78)
        at org.springframework.extensions.surf.render.bean.ChromeRenderer.render(ChromeRenderer.java:87)
        at org.springframework.extensions.surf.render.RenderService.processComponent(RenderService.java:435)
        at org.springframework.extensions.surf.render.bean.ComponentRenderer.body(ComponentRenderer.java:95)
        at org.springframework.extensions.surf.render.AbstractRenderer.render(AbstractRenderer.java:78)
        at org.springframework.extensions.surf.render.RenderService.renderComponent(RenderService.java:970)
        at org.springframework.extensions.surf.render.RenderService.renderRegionComponents(RenderService.java:909)
        at org.springframework.extensions.surf.render.RenderService.renderChromeInclude(RenderService.java:1273)
        at org.springframework.extensions.directives.ChromeIncludeFreeMarkerDirective.execute(ChromeIncludeFreeMarkerDirective.java:82)
        at freemarker.core.Environment.visit(Environment.java:341)
        at freemarker.core.UnifiedCall.accept(UnifiedCall.java:136)
        at freemarker.core.Environment.visit(Environment.java:265)
        at freemarker.core.MixedContent.accept(MixedContent.java:93)
        at freemarker.core.Environment.visit(Environment.java:265)
        at freemarker.core.Environment.process(Environment.java:243)
        at org.springframework.extensions.webscripts.processor.FTLTemplateProcessor.process(FTLTemplateProcessor.java:192)
        at org.springframework.extensions.webscripts.WebTemplateProcessor.executeBody(WebTemplateProcessor.java:439)
        at org.springframework.extensions.surf.render.AbstractProcessor.execute(AbstractProcessor.java:58)
        at org.springframework.extensions.surf.render.RenderService.processRenderable(RenderService.java:206)
        at org.springframework.extensions.surf.render.bean.ChromeRenderer.body(ChromeRenderer.java:96)
        at org.springframework.extensions.surf.render.AbstractRenderer.render(AbstractRenderer.java:78)
        at org.springframework.extensions.surf.render.bean.ChromeRenderer.render(ChromeRenderer.java:87)
        at org.springframework.extensions.surf.render.bean.RegionRenderer.body(RegionRenderer.java:100)
        at org.springframework.extensions.surf.render.AbstractRenderer.render(AbstractRenderer.java:78)
        at org.springframework.extensions.surf.render.RenderService.renderRegion(RenderService.java:858)
        at org.springframework.extensions.directives.RegionDirectiveData.render(RegionDirectiveData.java:92)
        at org.springframework.extensions.surf.extensibility.impl.ExtensibilityModelImpl.merge(ExtensibilityModelImpl.java:414)
        at org.springframework.extensions.surf.extensibility.impl.AbstractExtensibilityDirective.merge(AbstractExtensibilityDirective.java:170)
        at org.springframework.extensions.surf.extensibility.impl.AbstractExtensibilityDirective.execute(AbstractExtensibilityDirective.java:137)
        at freemarker.core.Environment.visit(Environment.java:341)
        at freemarker.core.UnifiedCall.accept(UnifiedCall.java:136)
        at freemarker.core.Environment.visitByHiddingParent(Environment.java:286)
        at freemarker.core.IteratorBlock$Context.runLoop(IteratorBlock.java:193)
        at freemarker.core.Environment.visitIteratorBlock(Environment.java:509)
        at freemarker.core.IteratorBlock.accept(IteratorBlock.java:103)
        at freemarker.core.Environment.visit(Environment.java:265)
        at freemarker.core.MixedContent.accept(MixedContent.java:93)
        at freemarker.core.Environment.visitByHiddingParent(Environment.java:286)
        at freemarker.core.IteratorBlock$Context.runLoop(IteratorBlock.java:193)
        at freemarker.core.Environment.visitIteratorBlock(Environment.java:509)
        at freemarker.core.IteratorBlock.accept(IteratorBlock.java:103)
        at freemarker.core.Environment.visit(Environment.java:265)
        at freemarker.core.MixedContent.accept(MixedContent.java:93)
        at freemarker.core.Environment.visit(Environment.java:265)
        at freemarker.core.Macro$Context.runMacro(Macro.java:209)
        at freemarker.core.Environment.visit(Environment.java:694)
        at freemarker.core.UnifiedCall.accept(UnifiedCall.java:116)
        at freemarker.core.Environment.visit(Environment.java:265)
        at freemarker.core.IfBlock.accept(IfBlock.java:84)
        at freemarker.core.Environment.visit(Environment.java:265)
        at freemarker.core.Macro$Context.runMacro(Macro.java:209)
        at freemarker.core.Environment.visit(Environment.java:694)
        at freemarker.core.UnifiedCall.accept(UnifiedCall.java:116)
        at freemarker.core.Environment.visit(Environment.java:265)
        at freemarker.core.MixedContent.accept(MixedContent.java:93)
        at freemarker.core.Environment.visit(Environment.java:265)
        at freemarker.core.Environment$1.render(Environment.java:313)
        at org.springframework.extensions.surf.extensibility.impl.DefaultExtensibilityDirectiveData.render(DefaultExtensibilityDirectiveData.java:119)
        at org.springframework.extensions.surf.extensibility.impl.ExtensibilityModelImpl.merge(ExtensibilityModelImpl.java:414)
        at org.springframework.extensions.surf.extensibility.impl.AbstractExtensibilityDirective.merge(AbstractExtensibilityDirective.java:170)
        at org.springframework.extensions.surf.extensibility.impl.AbstractExtensibilityDirective.execute(AbstractExtensibilityDirective.java:137)
        at freemarker.core.Environment.visit(Environment.java:341)
        at freemarker.core.UnifiedCall.accept(UnifiedCall.java:136)
        at freemarker.core.Environment.visit(Environment.java:265)
        at freemarker.core.MixedContent.accept(MixedContent.java:93)
        at freemarker.core.Environment.visit(Environment.java:265)
        at freemarker.core.Environment.visit(Environment.java:487)
        at freemarker.core.BodyInstruction.accept(BodyInstruction.java:93)
        at freemarker.core.Environment.visit(Environment.java:265)
        at freemarker.core.MixedContent.accept(MixedContent.java:93)
        at freemarker.core.Environment.visit(Environment.java:265)
        at freemarker.core.Macro$Context.runMacro(Macro.java:209)
        at freemarker.core.Environment.visit(Environment.java:694)
        at freemarker.core.UnifiedCall.accept(UnifiedCall.java:116)
        at freemarker.core.Environment.visit(Environment.java:265)
        at freemarker.core.MixedContent.accept(MixedContent.java:93)
        at freemarker.core.Environment.visit(Environment.java:265)
        at freemarker.core.Environment.process(Environment.java:243)
        at org.springframework.extensions.webscripts.processor.FTLTemplateProcessor.process(FTLTemplateProcessor.java:192)
        at org.springframework.extensions.webscripts.WebTemplateProcessor.executeBody(WebTemplateProcessor.java:439)
        at org.springframework.extensions.surf.render.AbstractProcessor.execute(AbstractProcessor.java:58)
        at org.springframework.extensions.surf.render.RenderService.processTemplate(RenderService.java:724)
        at org.springframework.extensions.surf.render.bean.TemplateInstanceRenderer.body(TemplateInstanceRenderer.java:142)
        at org.springframework.extensions.surf.render.AbstractRenderer.render(AbstractRenderer.java:78)
        at org.springframework.extensions.surf.render.bean.PageRenderer.body(PageRenderer.java:86)
        at org.springframework.extensions.surf.render.AbstractRenderer.render(AbstractRenderer.java:78)
        at org.springframework.extensions.surf.render.RenderService.renderPage(RenderService.java:770)
        at org.springframework.extensions.surf.mvc.PageView.dispatchPage(PageView.java:412)
        at org.springframework.extensions.surf.mvc.PageView.renderView(PageView.java:307)
        at org.springframework.extensions.surf.mvc.AbstractWebFrameworkView.renderMergedOutputModel(AbstractWebFrameworkView.java:321)
        at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:264)
        at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1216)
        at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1001)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:945)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:867)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:951)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:842)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:827)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.springframework.extensions.webscripts.servlet.SecurityHeadersFilter.doFilter(SecurityHeadersFilter.java:177)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.springframework.extensions.webscripts.servlet.CSRFFilter.doFilter(CSRFFilter.java:315)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.alfresco.web.site.servlet.SSOAuthenticationFilter.doFilter(SSOAuthenticationFilter.java:474)
        at org.alfresco.web.site.servlet.SSOAuthenticationFilter.doFilter(SSOAuthenticationFilter.java:443)
        at org.springframework.extensions.webscripts.servlet.BeanProxyFilter.doFilter(BeanProxyFilter.java:80)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.alfresco.web.site.servlet.MTAuthenticationFilter.doFilter(MTAuthenticationFilter.java:81)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:94)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:492)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1152)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1539)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1495)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.extensions.webscripts.WebScriptException: 10120000 10120001 Failed during processing of IMAP server status configuration from Alfresco: 10120000 Unable to retrieve IMAP server s                                                                                tatus from Alfresco: 401
        at org.springframework.extensions.webscripts.processor.JSScriptProcessor.executeScriptImpl(JSScriptProcessor.java:339)
        at org.springframework.extensions.webscripts.processor.JSScriptProcessor.executeScript(JSScriptProcessor.java:209)
        ... 161 more
Caused by: org.alfresco.error.AlfrescoRuntimeException: 10120001 Failed during processing of IMAP server status configuration from Alfresco: 10120000 Unable to retrieve IMAP server status from Alfresco: 401
        at org.alfresco.web.scripts.SingletonValueProcessorExtension.getSingletonValue(SingletonValueProcessorExtension.java:126)
        at org.alfresco.web.scripts.SingletonValueProcessorExtension.getSingletonValue(SingletonValueProcessorExtension.java:78)
        at org.alfresco.web.scripts.SingletonValueProcessorExtension.getSingletonValue(SingletonValueProcessorExtension.java:66)
        at org.alfresco.web.scripts.ImapServerStatus.getEnabled(ImapServerStatus.java:56)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
        at org.mozilla.javascript.JavaMembers.get(JavaMembers.java:85)
        at org.mozilla.javascript.NativeJavaObject.get(NativeJavaObject.java:77)
        at org.mozilla.javascript.ScriptableObject.getProperty(ScriptableObject.java:2184)
        at org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1492)
        at org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1485)
        at org.mozilla.javascript.gen.file__opt_alfresco_tomcat_webapps_share_WEB_INF_classes_alfresco_site_webscripts_org_alfresco_components_dashlets_my_sites_get_js_6._c_main_1(file:/opt/alfresco/tomcat/we                                                                                bapps/share/WEB-INF/classes/alfresco/site-webscripts/org/alfresco/components/dashlets/my-sites.get.js:4)
        at org.mozilla.javascript.gen.file__opt_alfresco_tomcat_webapps_share_WEB_INF_classes_alfresco_site_webscripts_org_alfresco_components_dashlets_my_sites_get_js_6.call(file:/opt/alfresco/tomcat/webapps                                                                                /share/WEB-INF/classes/alfresco/site-webscripts/org/alfresco/components/dashlets/my-sites.get.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callName0(OptRuntime.java:74)
        at org.mozilla.javascript.gen.file__opt_alfresco_tomcat_webapps_share_WEB_INF_classes_alfresco_site_webscripts_org_alfresco_components_dashlets_my_sites_get_js_6._c_script_0(file:/opt/alfresco/tomcat/                                                                                webapps/share/WEB-INF/classes/alfresco/site-webscripts/org/alfresco/components/dashlets/my-sites.get.js:52)
        at org.mozilla.javascript.gen.file__opt_alfresco_tomcat_webapps_share_WEB_INF_classes_alfresco_site_webscripts_org_alfresco_components_dashlets_my_sites_get_js_6.call(file:/opt/alfresco/tomcat/webapps                                                                                /share/WEB-INF/classes/alfresco/site-webscripts/org/alfresco/components/dashlets/my-sites.get.js)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
        at org.mozilla.javascript.gen.file__opt_alfresco_tomcat_webapps_share_WEB_INF_classes_alfresco_site_webscripts_org_alfresco_components_dashlets_my_sites_get_js_6.call(file:/opt/alfresco/tomcat/webapps                                                                                /share/WEB-INF/classes/alfresco/site-webscripts/org/alfresco/components/dashlets/my-sites.get.js)
        at org.mozilla.javascript.gen.file__opt_alfresco_tomcat_webapps_share_WEB_INF_classes_alfresco_site_webscripts_org_alfresco_components_dashlets_my_sites_get_js_6.exec(file:/opt/alfresco/tomcat/webapps                                                                                /share/WEB-INF/classes/alfresco/site-webscripts/org/alfresco/components/dashlets/my-sites.get.js)
        at org.springframework.extensions.webscripts.processor.JSScriptProcessor.executeScriptImpl(JSScriptProcessor.java:333)
        ... 162 more
After this failure I removed the comments from alfresco-global.properties for the IMAP section but that didn't solve it.

**Comment by loftux** [comment]
Sorry, I cannot give support for errors that are not script errors.
Please Join discord and ask there https://discordapp.com/invite/f7XntQN
