### ISSUE TITLE
repository is not starting : may be issue with deploying alfresco.xml.

### ISSUE THREAD

**Issue by monicakumari** [loftuxab/alfresco-ubuntu-install#141]
Hello, I have followed all instructions and after installating, I have started alfresco service but its getting the error in the middle of the logs on console. Share is working but alfresco side is not working. I have updated tomcat memory setting  JAVA_OPTS="-Xms1G -Xmx8G -Xss1024m"
 in alfresco-service.sh file but still getting the same error. my system configurations are : 6 cpu and 16 gb ram. Its not VM but my PC and this is the third PC on which I am trying to do it. 

I did this before multiple times, it was working fine then. don't know now why this is happening.
Please guide. 

> 12-May-2020 12:25:52.476 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDescriptor Deploying configuration descriptor /opt/alfresco/tomcat/conf/Catalina/localhost/alfresco.xml
12-May-2020 12:26:26.969 SEVERE [localhost-startStop-1] org.apache.catalina.core.ContainerBase.addChildInternal ContainerBase.addChild: start: 
 org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/alfresco]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:162)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:755)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:731)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:620)
	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1832)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Unable to complete the scan for annotations for web application [/alfresco] due to a StackOverflowError. Possible root causes include a too low setting for -Xss and illegal cyclic inheritance dependencies. The class hierarchy being processed was [org.bouncycastle.asn1.ASN1Boolean->org.bouncycastle.asn1.DERBoolean->org.bouncycastle.asn1.ASN1Boolean]
	at org.apache.catalina.startup.ContextConfig.checkHandlesTypes(ContextConfig.java:2098)
	at org.apache.catalina.startup.ContextConfig.processAnnotationsStream(ContextConfig.java:2044)
	at org.apache.catalina.startup.ContextConfig.processAnnotationsJar(ContextConfig.java:1989)
	at org.apache.catalina.startup.ContextConfig.processAnnotationsUrl(ContextConfig.java:1959)
	at org.apache.catalina.startup.ContextConfig.processAnnotations(ContextConfig.java:1913)
	at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1156)
	at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:773)
	at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:307)
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:95)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5262)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	... 10 more

> 12-May-2020 12:26:26.970 SEVERE [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDescriptor Error deploying configuration descriptor /opt/alfresco/tomcat/conf/Catalina/localhost/alfresco.xml
 java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/alfresco]]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:759)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:731)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:620)
	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1832)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Thanks.

**Comment by douglascrp** [comment]
Hello.

Do you have any addon in place?
I have seen errors involving BouncyCastle when I use addons dealing with PDF and digital signing.
If that is the case, it means the addon is not compatible with the Alfresco version.

**Comment by monicakumari** [comment]
Thank you. I got to know something new.
Yes it was due to my custom code. I'll upgrade them, surely they will work fine.

Thanks .
