### ISSUE TITLE
Even after outdated Postgres JDBC and Tomcat urls are fixed, Alfresco fails to run.

### ISSUE THREAD

**Issue by chris001** [loftuxab/alfresco-ubuntu-install#44]
Fixed outdated Postgresl JDBC and Tomcat urls in the script.
The script completes. 
Make the requested modifications - database username password and type - to the start script.
Alfresco still fails to come up fully.
Java process runs, but web interface shows "Alfresco Maintenance. Alfresco down for maintenance "
The log fills up very fast.  100MB in about 12 hours.  
All the same entries repeating.
Here is the last 100 lines of /var/log/upstart/alfresco.log

19-Feb-2015 14:43:23.799 SEVERE [main] org.apache.tomcat.util.digester.Digester.
startElement Begin event threw exception
 java.lang.ClassNotFoundException: org.apache.catalina.core.JasperListener
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at org.apache.tomcat.util.digester.ObjectCreateRule.begin(ObjectCreateRu
le.java:116)
        at org.apache.tomcat.util.digester.Digester.startElement(Digester.java:1
184)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startEle
ment(AbstractSAXParser.java:509)
        at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.
emptyElement(AbstractXMLDocumentParser.java:182)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImp
l.scanStartElement(XMLDocumentFragmentScannerImpl.java:1343)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImp
l$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2786)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(X
MLDocumentScannerImpl.java:606)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImp
l.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(X
ML11Configuration.java:848)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(X
ML11Configuration.java:777)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.
java:141)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Ab
stractSAXParser.java:1213)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.p
arse(SAXParserImpl.java:648)
        at org.apache.tomcat.util.digester.Digester.parse(Digester.java:1457)
        at org.apache.catalina.startup.Catalina.load(Catalina.java:551)
        at org.apache.catalina.startup.Catalina.start(Catalina.java:613)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:351)
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:485)

19-Feb-2015 14:43:23.803 WARNING [main] org.apache.catalina.startup.Catalina.loa
d Catalina.start using conf/server.xml: Error at (30, 67) : org.apache.catalina.
core.JasperListener
19-Feb-2015 14:43:23.804 SEVERE [main] org.apache.catalina.startup.Catalina.star
t Cannot start server. Server instance is not configured.
*** ALERT - A stop was issued before Alfresco was properly started. In 120 secon
ds server will stop. ***
19-Feb-2015 14:43:25.054 SEVERE [main] org.apache.tomcat.util.digester.Digester.
startElement Begin event threw exception
 java.lang.ClassNotFoundException: org.apache.catalina.core.JasperListener
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at org.apache.tomcat.util.digester.ObjectCreateRule.begin(ObjectCreateRu
le.java:116)
        at org.apache.tomcat.util.digester.Digester.startElement(Digester.java:1
184)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startEle
ment(AbstractSAXParser.java:509)
        at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.
emptyElement(AbstractXMLDocumentParser.java:182)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImp
l.scanStartElement(XMLDocumentFragmentScannerImpl.java:1343)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImp
l$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2786)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(X
MLDocumentScannerImpl.java:606)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImp
l.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(X
ML11Configuration.java:848)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(X
ML11Configuration.java:777)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.
java:141)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Ab
stractSAXParser.java:1213)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.p
arse(SAXParserImpl.java:648)
        at org.apache.tomcat.util.digester.Digester.parse(Digester.java:1457)
        at org.apache.catalina.startup.Catalina.load(Catalina.java:551)
        at org.apache.catalina.startup.Catalina.load(Catalina.java:599)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.catalina.startup.Bootstrap.load(Bootstrap.java:310)
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:484)

19-Feb-2015 14:43:25.072 WARNING [main] org.apache.catalina.startup.Catalina.loa
d Catalina.start using conf/server.xml: Error at (30, 67) : org.apache.catalina.
core.JasperListener
19-Feb-2015 14:43:25.096 SEVERE [main] org.apache.tomcat.util.digester.Digester.
startElement Begin event threw exception
 java.lang.ClassNotFoundException: org.apache.catalina.core.JasperListener
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at org.apache.tomcat.util.digester.ObjectCreateRule.begin(ObjectCreateRu
le.java:116)
        at org.apache.tomcat.util.digester.Digester.startElement(Digester.java:1
184)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startEle
ment(AbstractSAXParser.java:509)
        at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.
emptyElement(AbstractXMLDocumentParser.java:182)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImp
l.scanStartElement(XMLDocumentFragmentScannerImpl.java:1343)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImp
l$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2786)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(X
MLDocumentScannerImpl.java:606)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImp
l.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(X
ML11Configuration.java:848)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(X
ML11Configuration.java:777)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.
java:141)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Ab
stractSAXParser.java:1213)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.p
arse(SAXParserImpl.java:648)
        at org.apache.tomcat.util.digester.Digester.parse(Digester.java:1457)
        at org.apache.catalina.startup.Catalina.load(Catalina.java:551)
        at org.apache.catalina.startup.Catalina.start(Catalina.java:613)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:351)
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:485)

19-Feb-2015 14:43:25.106 WARNING [main] org.apache.catalina.startup.Catalina.loa
d Catalina.start using conf/server.xml: Error at (30, 67) : org.apache.catalina.
core.JasperListener
19-Feb-2015 14:43:25.107 SEVERE [main] org.apache.catalina.startup.Catalina.star
t Cannot start server. Server instance is not configured.
script: open failed: typescript: Permission denied
~#

**Comment by loftux** [comment]
I just ran the entire script with the latest updates, and Alfresco started fine. Are you still trying with 32bit?

**Comment by chris001** [comment]
@loftux This error shows on a new VM with Ubuntu 14.04 x86_64 ... 64 bit.
Selected the option to run on Postgresql (with updated 4.1 url), Solr4, openjdk, tomcat 8 (had to update url).
Any idea why the error?

**Comment by loftux** [comment]
I have now run it again, this time with postgres, and it works fine.
The error indicates that there is an issue with the tomcat configuration files, check that they are correct (compare to the ones downloaded by the script). 
Unless you have a reliable way to reproduce the error I'm going to close the issue.

**Comment by chris001** [comment]
Steps to reproduce.
1. Replace Postgres JDBC URL with:
JDBCPOSTGRES=postgresql-9.3-1102.jdbc41.jar
2. Replace Tomcat URL with:
TOMCAT_DOWNLOAD=http://apache.mirrors.spacedump.net/tomcat/tomcat-8/v8.0.18.tar.gz
3. Run alfinstall.sh
Install everything (enter y to all yes/no prompts ).
http as protocol type for both share and alfresco repository.
Script completes installation.
Make modifications requested by script (db username, db password, db type postgres, comment out mysql db settings).
Start alfreso service.
You should see the error log filling up quickly.
/var/log/alfresco/upstart/alfresco.log

**Comment by loftux** [comment]
The current supported version is Tomcat 7. You will have to merge the files in https://github.com/loftuxab/alfresco-ubuntu-install/tree/master/tomcat catalina.properties and server.xml. the script has downloaded those and overwritten the version 8 ones with version 7 compatible ones. There is your error. You have to manually make sure that you use working versions.

**Comment by chris001** [comment]
Thanks @loftux 
http://www.coderanch.com/t/84854/Tomcat/solve-erro-tomcat-console
Any thought of adding support for tomcat 8 by detecting downloaded tomcat version and then select matching version of catalina.properties and server.xml to download?

Also: alfresco 5 has html5 document preview, swf flash in Alfresco is deprecated as unnecessary. Isn't it now best to remove the swftools installer from the script?
http://blogs.alfresco.com/wp/kevinr/2014/06/27/alfresco-community-5-0-a/

**Comment by chris001** [comment]
It's still throwing the same errors when installing Tomcat 7.
TOMCAT_DOWNLOAD=http://apache.mesi.com.ar/tomcat/tomcat-7/v7.0.59/bin/apache-tomcat-7.0.59.tar.gz

/var/log/alfresco/upstart/alfresco.log

20-Feb-2015 18:13:28.513 WARNING [main] org.apache.catalina.startup.Catalina.load Catalina.start using conf/server.xml: Error at (30, 67) : org.apache.catalina.core.JasperListener
20-Feb-2015 18:13:28.534 SEVERE [main] org.apache.tomcat.util.digester.Digester.startElement Begin event threw exception
 java.lang.ClassNotFoundException: org.apache.catalina.core.JasperListener

Lines 29 and 30 of server.xml:

<Listener className="org.apache.catalina.core.JasperListener" />

**Comment by chris001** [comment]
@loftux I found the cause of the problem.
The script created 2 tomcat lib folders in the /opt/alfresco/ tree.
One called tomcat, the other called tomcat-(full version number) - obviously leftover when the script failed to remove it.
Must be a bug, when you reinstall over an existing failed install, where the script fails to remove the existing tomcat folder, and leaves the uncompressed tomcat-(version). folder in place, to cause this class not found crash bug...
There was a set of Tomcat 8 libs (jars) in one folder, and a set of Tomcat 7 libs (jars) in the other folder.
The Tomcat java classloader was taking the incompatible Tomcat 8 version of the jasper.jar (JSP page support).
It would be a lot better if the Tomcat Java error log message actually said, "incompatible library version," and gave the full path of the offending jar.... Jeez...
Problem solved by removing both "tomcat" folders (each of which contained a lib folder full of jars) and re-run the install script from beginning.

**Comment by loftux** [comment]
Opened a separate issue for Tomcat 8, Java 8 support #47 
Opened a separate issue for removing swftools. #48
Closing this issue.
