### ISSUE TITLE
solr SEVERE Exception opening zip file. Null pointer exception. Etc.

### ISSUE THREAD

**Issue by chris001** [loftuxab/alfresco-ubuntu-install#51]
Have posted this login error issue on Alfresco forum.

They think this solr4 error is the reason why the initial login is failing:

>Looking at catalina.out, the solr4 web application is failing to load because there is a problem with the config file solr.xml.
>
>I'm not sure why solr would be relevant to a log in, but certainly without it Alfresco will not function. Also the fact that it is aborting may be killing some components that Alfresco login relies upon.
>
>First order of business is to adjust the solr config so that it will load & run"

Catalina.log:

		Feb 25, 2015 8:49:10 PM org.apache.catalina.startup.VersionLoggerListener log
		INFO: Server version:        Apache Tomcat/7.0.59
		Feb 25, 2015 8:49:10 PM org.apache.catalina.startup.VersionLoggerListener log
		INFO: Server built:          Jan 28 2015 15:51:10 UTC
		Feb 25, 2015 8:49:10 PM org.apache.catalina.startup.VersionLoggerListener log
		INFO: Server number:         7.0.59.0
		Feb 25, 2015 8:49:10 PM org.apache.catalina.startup.VersionLoggerListener log
		INFO: OS Name:               Linux
		Feb 25, 2015 8:49:10 PM org.apache.catalina.startup.VersionLoggerListener log
		INFO: OS Version:            2.6.32-32-pve
		Feb 25, 2015 8:49:10 PM org.apache.catalina.startup.VersionLoggerListener log
		INFO: Architecture:          amd64
		Feb 25, 2015 8:49:10 PM org.apache.catalina.startup.VersionLoggerListener log
		INFO: Java Home:             /usr/lib/jvm/java-7-openjdk-amd64/jre
		Feb 25, 2015 8:49:10 PM org.apache.catalina.startup.VersionLoggerListener log
		INFO: JVM Version:           1.7.0_75-b13
		Feb 25, 2015 8:49:10 PM org.apache.catalina.startup.VersionLoggerListener log
		INFO: JVM Vendor:            Oracle Corporation
		Feb 25, 2015 8:49:10 PM org.apache.catalina.startup.VersionLoggerListener log
		INFO: CATALINA_BASE:         /opt/alfresco/tomcat
		Feb 25, 2015 8:49:10 PM org.apache.catalina.startup.VersionLoggerListener log
		INFO: CATALINA_HOME:         /opt/alfresco/tomcat
		Feb 25, 2015 8:49:10 PM org.apache.catalina.startup.VersionLoggerListener log
		INFO: Command line argument: -Djava.util.logging.config.file=/opt/alfresco/tomcat/conf/logging.properties
		Feb 25, 2015 8:49:10 PM org.apache.catalina.startup.VersionLoggerListener log
		INFO: Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
		Feb 25, 2015 8:49:10 PM org.apache.catalina.startup.VersionLoggerListener log
		INFO: Command line argument: -Xms2G
		Feb 25, 2015 8:49:10 PM org.apache.catalina.startup.VersionLoggerListener log
		INFO: Command line argument: -Xmx3G
		Feb 25, 2015 8:49:10 PM org.apache.catalina.startup.VersionLoggerListener log
		INFO: Command line argument: -Xss1024k
		Feb 25, 2015 8:49:10 PM org.apache.catalina.startup.VersionLoggerListener log
		INFO: Command line argument: -XX:MaxPermSize=256m
		Feb 25, 2015 8:49:10 PM org.apache.catalina.startup.VersionLoggerListener log
		INFO: Command line argument: -Duser.country=US
		Feb 25, 2015 8:49:10 PM org.apache.catalina.startup.VersionLoggerListener log
		INFO: Command line argument: -Duser.region=US
		Feb 25, 2015 8:49:10 PM org.apache.catalina.startup.VersionLoggerListener log
		INFO: Command line argument: -Duser.language=en
		Feb 25, 2015 8:49:10 PM org.apache.catalina.startup.VersionLoggerListener log
		INFO: Command line argument: -Duser.timezone=Europe/Stockholm
		Feb 25, 2015 8:49:10 PM org.apache.catalina.startup.VersionLoggerListener log
		INFO: Command line argument: -Dfile.encoding=UTF-8
		Feb 25, 2015 8:49:10 PM org.apache.catalina.startup.VersionLoggerListener log
		INFO: Command line argument: -Dsun.jnu.encoding=UTF-8
		Feb 25, 2015 8:49:10 PM org.apache.catalina.startup.VersionLoggerListener log
		INFO: Command line argument: -Dalfresco.home=/opt/alfresco
		Feb 25, 2015 8:49:10 PM org.apache.catalina.startup.VersionLoggerListener log
		INFO: Command line argument: -Dcom.sun.management.jmxremote=true
		Feb 25, 2015 8:49:10 PM org.apache.catalina.startup.VersionLoggerListener log
		INFO: Command line argument: -Djava.endorsed.dirs=/opt/alfresco/tomcat/endorsed
		Feb 25, 2015 8:49:10 PM org.apache.catalina.startup.VersionLoggerListener log
		INFO: Command line argument: -Dcatalina.base=/opt/alfresco/tomcat
		Feb 25, 2015 8:49:10 PM org.apache.catalina.startup.VersionLoggerListener log
		INFO: Command line argument: -Dcatalina.home=/opt/alfresco/tomcat
		Feb 25, 2015 8:49:10 PM org.apache.catalina.startup.VersionLoggerListener log
		INFO: Command line argument: -Djava.io.tmpdir=/opt/alfresco/tomcat/temp
		Feb 25, 2015 8:49:10 PM org.apache.catalina.core.AprLifecycleListener lifecycleEvent
		INFO: Loaded APR based Apache Tomcat Native library 1.1.32 using APR version 1.5.1.
		Feb 25, 2015 8:49:10 PM org.apache.catalina.core.AprLifecycleListener lifecycleEvent
		INFO: APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
		Feb 25, 2015 8:49:10 PM org.apache.catalina.core.AprLifecycleListener initializeSSL
		INFO: OpenSSL successfully initialized (OpenSSL 1.0.1f 6 Jan 2014)
		Feb 25, 2015 8:49:10 PM org.apache.coyote.AbstractProtocol init
		INFO: Initializing ProtocolHandler ["http-apr-8080"]
		Feb 25, 2015 8:49:10 PM org.apache.coyote.AbstractProtocol init
		INFO: Initializing ProtocolHandler ["http-bio-8443"]
		Feb 25, 2015 8:49:11 PM org.apache.coyote.AbstractProtocol init
		INFO: Initializing ProtocolHandler ["ajp-apr-8009"]
		Feb 25, 2015 8:49:11 PM org.apache.catalina.startup.Catalina load
		INFO: Initialization processed in 2621 ms
		Feb 25, 2015 8:49:11 PM org.apache.catalina.core.StandardService startInternal
		INFO: Starting service Catalina
		Feb 25, 2015 8:49:11 PM org.apache.catalina.core.StandardEngine startInternal
		INFO: Starting Servlet Engine: Apache Tomcat/7.0.59
		Feb 25, 2015 8:49:11 PM org.apache.catalina.startup.HostConfig deployDescriptor
		INFO: Deploying configuration descriptor /opt/alfresco/tomcat/conf/Catalina/localhost/solr4.xml
		Feb 25, 2015 8:49:11 PM org.apache.catalina.startup.SetContextPropertiesRule begin
		WARNING: [SetContextPropertiesRule]{Context} Setting property 'debug' to '0' did not find a matching property.
		Feb 25, 2015 8:49:11 PM org.apache.catalina.startup.ContextConfig beforeStart
		SEVERE: Exception fixing docBase for context [/solr4]
		java.util.zip.ZipException: error in opening zip file
			at java.util.zip.ZipFile.open(Native Method)
			at java.util.zip.ZipFile.<init>(ZipFile.java:215)
			at java.util.zip.ZipFile.<init>(ZipFile.java:145)
			at java.util.jar.JarFile.<init>(JarFile.java:154)
			at java.util.jar.JarFile.<init>(JarFile.java:91)
			at sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:93)
			at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:69)
			at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:99)
			at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:122)
			at sun.net.www.protocol.jar.JarURLConnection.getJarFile(JarURLConnection.java:89)
			at org.apache.catalina.startup.ExpandWar.expand(ExpandWar.java:111)
			at org.apache.catalina.startup.ContextConfig.fixDocBase(ContextConfig.java:754)
			at org.apache.catalina.startup.ContextConfig.beforeStart(ContextConfig.java:863)
			at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:388)
			at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
			at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
			at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:402)
			at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
			at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
			at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
			at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649)
			at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:672)
			at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1859)
			at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
			at java.util.concurrent.FutureTask.run(FutureTask.java:262)
			at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
			at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
			at java.lang.Thread.run(Thread.java:745)

		Feb 25, 2015 8:49:11 PM org.apache.catalina.core.StandardContext resourcesStart
		SEVERE: Error starting static Resources
		java.lang.NullPointerException
			at java.io.File.<init>(File.java:277)
			at org.apache.catalina.core.StandardContext.getBasePath(StandardContext.java:6065)
			at org.apache.catalina.core.StandardContext.resourcesStart(StandardContext.java:5141)
			at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5326)
			at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
			at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
			at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
			at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649)
			at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:672)
			at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1859)
			at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
			at java.util.concurrent.FutureTask.run(FutureTask.java:262)
			at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
			at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
			at java.lang.Thread.run(Thread.java:745)

		Feb 25, 2015 8:49:11 PM org.apache.catalina.core.ContainerBase addChildInternal
		SEVERE: ContainerBase.addChild: start: 
		org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/solr4]]
			at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
			at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
			at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
			at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649)
			at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:672)
			at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1859)
			at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
			at java.util.concurrent.FutureTask.run(FutureTask.java:262)
			at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
			at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
			at java.lang.Thread.run(Thread.java:745)
		Caused by: org.apache.catalina.LifecycleException: Error in resourceStart()
			at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5327)
			at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
			... 10 more

		Feb 25, 2015 8:49:11 PM org.apache.catalina.startup.HostConfig deployDescriptor
		SEVERE: Error deploying configuration descriptor /opt/alfresco/tomcat/conf/Catalina/localhost/solr4.xml
		java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/solr4]]
		    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:904)
		    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
		    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649)
		    at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:672)
		    at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1859)
		    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
		    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
		    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
		    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
		    at java.lang.Thread.run(Thread.java:745)

		Feb 25, 2015 8:49:11 PM org.apache.catalina.startup.HostConfig deployDescriptor
		INFO: Deployment of configuration descriptor /opt/alfresco/tomcat/conf/Catalina/localhost/solr4.xml has finished in 182 ms
		Feb 25, 2015 8:49:11 PM org.apache.catalina.startup.HostConfig deployWAR
		INFO: Deploying web application archive /opt/alfresco/tomcat/webapps/alfresco.war
		Feb 25, 2015 8:51:38 PM org.apache.catalina.startup.HostConfig deployWAR
		INFO: Deployment of web application archive /opt/alfresco/tomcat/webapps/alfresco.war has finished in 146,336 ms
		Feb 25, 2015 8:51:38 PM org.apache.catalina.startup.HostConfig deployWAR
		INFO: Deploying web application archive /opt/alfresco/tomcat/webapps/share.war
		Feb 25, 2015 8:52:05 PM org.apache.catalina.startup.HostConfig deployWAR
		INFO: Deployment of web application archive /opt/alfresco/tomcat/webapps/share.war has finished in 27,111 ms
		Feb 25, 2015 8:52:05 PM org.apache.coyote.AbstractProtocol start
		INFO: Starting ProtocolHandler ["http-apr-8080"]
		Feb 25, 2015 8:52:05 PM org.apache.coyote.AbstractProtocol start
		INFO: Starting ProtocolHandler ["http-bio-8443"]
		Feb 25, 2015 8:52:05 PM org.apache.coyote.AbstractProtocol start
		INFO: Starting ProtocolHandler ["ajp-apr-8009"]
		Feb 25, 2015 8:52:05 PM org.apache.catalina.startup.Catalina start
		INFO: Server startup in 173846 ms

**Comment by loftux** [comment]
Is this issue different than your proved fix for the solr4 dowload url check?

**Comment by chris001** [comment]
The cause of this "SEVERE exception" issue, has been determined, solr4.war was an incompletely downloaded file.
Downloaded somehow stopped at 19MB, the full proper war file is 99MB.
Fixed by manually downloading and setting ownership.
This would be prevented from happening with the planned checksum support.
(Now login is still failing, but at least it's not because of a failed deployment of solr4.war - alfresco starts and depolys all wars with no errors whatsoever.)

**Comment by loftux** [comment]
Closing this as there is an issue to add checksum support: #23
